version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: shipflow-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shipflow
      POSTGRES_PASSWORD: shipflow_secret
      POSTGRES_DB: shipflow
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
