packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: true

overrides:
  postcss: "^8.5.10"
  "@hono/node-server": "^1.19.13"
